% \VignetteIndexEntry{BDgraph: An R Package for Bayesian Structure Learning in Graphical Models}
% \VignetteKeywords{Bayesian structure learning, Gaussian graphical models, Gaussian copula, Covariance selection, Birth-death process, G-Wishart, BDgraph}
% \VignettePackage{package BDgraph}

\documentclass[a4paper]{article}
\usepackage{hyperref}
\usepackage{pdfpages}
\begin{document}
\includepdf[fitpaper=true,pages=-]{BDgraph.pdf}
\end{document}
