% \VignetteIndexEntry{An Introduction to the BDgraph Package for Bayesian Graphical Models}
% \VignetteKeywords{Bayesian structure learning, Gaussian graphical models, Gaussian copula, Covariance selection, Birth-death process, G-Wishart, BDgraph}
% \VignettePackage{BDgraph}

\documentclass[a4paper]{article}
\usepackage{hyperref}
\usepackage{pdfpages}
\begin{document}
\includepdf[fitpaper=true,pages=-]{BDgraph.pdf}
\end{document}
